dist: xenial
language: python
services:
- docker
script:
- make build -t tamanio-poblacional-aves-marinas .
after_success:
- secure: docker save tamanio-poblacional-aves-marinas:latest | ssh -C ${SERVIDOR_VPS}@${USUARIO_VPS} docker load
