dist: xenial
language: python
services:
- docker
script:
- make build
after_success:
- docker save tamanio-poblacional-aves-marinas:latest | ssh -oStrictHostKeyChecking=no -C ${USUARIO_VPS}@${SERVIDOR_VPS} docker load
