dist: xenial
language: python
services:
- docker
addons:
    apt:
        packages:
            - sshpass
script:
- make build
after_success:
- docker save tamanio-poblacional-aves-marinas:latest | sshpass -p ${PASSWORD_SERVIDOR} ssh -oStrictHostKeyChecking=no -C ${USUARIO_VPS}@${SERVIDOR_VPS} docker load
